.travis.yml
setup.py

Python-semver is Python3-compatible, but it doesn't explicitly state so in `setup.py`.
I was warned about this in my project that uses python-semver: https://caniusepython3.com/check/00276696-d27c-46f0-b10e-0c7bd684f786

Explicitly show support for Python 3

---

MANIFEST.in

Installation is failing because the `MANIFEST.in` file does not contain `README.md`. This PR fixes that.

Include README.md in the manifest

---

semver.py

Fixed an issue when I'm trying to compare('0.10.1-rc1', '0.10.1-rc0')

Fix a bug with comparing rc0 vs rc1

---

semver.py
tests/semver_test.py

I added bumping prerelease and build version. It works quite well, I just wasn't sure how semver should behave when we are going to bump prerelease or build on version 1.2.3, so I assume to append 'rc.1' / 'build.1' respectively instead of raising exception.

Add bumping prerelease and build versions

---

semver.py
tests/semver_test.py

I found a bug when versions with RC and build numbers were compared, for example:
```
>>> compare('1.1.9-rc.1', '1.1.9+build.1')
-1
>>> compare('1.1.9-rc.1', '1.1.9-rc.1+build.1')
0
```
It seems like comparision for build values was not implemented, so I added this in my PR :)

Fix bug in comparision between versions with build and prerelease

---

semver.py
tests.py

Match versions with a match expression meaning 'not equal', for example to explicitly exclude a specific version.
Remove check for unused/unsupported match expression '='.

Support matching 'not equal' with '!='

---

semver.py
tests.py

According to [Semantic Versioning 2.0.0](http://semver.org/):
> 10. ... Build metadata SHOULD be ignored when determining version precedence. ...
>
> 11. ... Precedence MUST be calculated by separating the version into major, minor, patch and pre-release identifiers in that order (Build metadata does not figure into precedence). ...
See spec items [10](http://semver.org/#spec-item-10) and [11](http://semver.org/#spec-item-11).
Changelog:
* Remove build metadata comparison in `compare_by_keys`
* Update `test_should_compare_versions_with_build_and_release`
* Add `test_should_ignore_builds_on_compare`

Remove comparison of build metadata

---

semver.py
tests.py

Fixes #45 
The logic implementing the prerelease version comparisons was not quite correct.
Modified how pre-release tags are compared to ensure that all of the example test vectors from the semver spec evaluate correctly.

fix version comparisons

---

semver.py
tests.py

I updated `VersionInfo` class to inherit from named tuple and I added rich comparison methods to allow compare between two `VersionInfo` instances or between `VersionInfo` and dictionary.
This PR should resolve issue #54.
Since we are still supporting Python 2.6 it was not possible to use [functools.total_ordering](https://docs.python.org/3.6/library/functools.html#functools.total_ordering).

Add comparision between VersionInfo objects

---

setup.py
tox.ini

Python 3.6 seems to be supported out of the box by library, I think it'll be nice to add official support for this version.

Add support for Python 3.6

---

.travis.yml

I updated a Travis config file to use Tox with tested Python version. It should fix problems with missing interpreter (see output [here](https://travis-ci.org/ppkt/python-semver)) and resolve issue #57.
I also noticed that there is a problem with Python 3.2 - I'll take a look on this problem in free time.

Update Travis configuration file

---

semver.py
tests.py

It looks like there were missing regex anchors for start/end line. I added them and test to verify fix.

Fix problem in `compare` when prerelease tag starts with number followed by letters

---

semver.py
tests.py

e.g. `dev` instead of `rc` or `nightly` instead of `build`

support custom default names for pre and build

---

CHANGELOG
semver.py
test_semver.py

[pytest.mark.parametrize](http://docs.pytest.org/en/latest/parametrize.html?highlight=parametrize#pytest-mark-parametrize-parametrizing-test-functions) has some benefits over multiple asserts:
* each test can be selected individually
* test code is just a one-liner
* adding more tests is just a matter of putting more data into the list
* gives you a more impressive amount of test cases 😉 
It works for me and creates 91 tests

Convert multiple tests into pytest.mark.parametrize

---

CHANGELOG
semver.py
tox.ini

Add doctests

---

CHANGELOG
semver.py

Remove namedtuple inheritance

---

CHANGELOG
semver.py
test_semver.py

Immutable VersionInfo

---

semver.py

The binary-operator comparison methods of the `VersionInfo` class all contain the same boilerplate type-checking code. This patch adds a decorator function that wraps these methods in the type-check logic, which allows the operator method implementations to be stripped down to single lines of code – whose legibility allows them to be readily scanned by newcomers to the project and others unfamiliar with the codebase.

Use a method decorator to deduplicate binary operator logic

---

semver.py
test_semver.py

* Raise `AttributeError` with useful messages for major, minor, patch, prerelease, and build attributes.
* Use [`pytest.raises` ](https://docs.pytest.org/en/latest/reference.html?highlight=pytest.raises#pytest-raises) which replace and shorten the `try..except..else` blocks.
* Use `match` keyword in pytest.raises which matches the `AttributeError` from the property setter.
* Split `test_immutable` into several different test functions,  e.g.` test_immutable_major`.
Some comments:
* I've splitted the `test_immutable` function into several other functions as IMHO it makes it more readable.
* If you don't like the property setter and prefer a more cleaner class, I can remove it. I merely added them to have a more correct error message raised which can …

Improve test_immutable function

---

tox.ini

Fix #121. Reduce command `python3.3` to `python3`.
With that patch, it works on Travis and locally. I consider the latter as essential as it doesn't force the user to have Python 3.4 installed. Every 3.x version is possible as long there is an executable or link to `python3`.

Use python3 instead of python3.4

---

semver.py

Improve __repr__ and derive class name from type

---

CONTRIBUTORS
semver.py
test_semver.py

This PR is based on #109 by Karol Werner and contains:
* Add Karl to the `CONTRIBUTORS` file and added him as primary author.
* Use `version` fixture in test function `test_version_info_should_be_iterable`.
* I've deviated from Karl's test function a bit and avoided the "private" `_astuple()` function and created the tuple manually.
* This PR does not contains a conflict. :wink: 
I think, Karol's idea is useful as it allows to create a list with just `tuple(version)` or `list(version)` without using the (kind of) "private" member function `_astuple()`.
If the maintainers of this project find it useful, I suggest to close #109 as well (as it is related and contains a conflict).

Fixes #109 and add iterator to VersionInfo

---

.coveragerc
setup.cfg
tox.ini

* Use `pytest` command instead of `py.test` (the latter with the dot may be obsolete in the future).
* Move options from `tox.ini` to `setup.cfg`.
* Introduce `pytest-cov` in "tox.ini" for coverage and config file `.coveragerc`
* Add additional options to activate coverage for `semver.py` script and output coverage report
---
Some comments:
* It simplifies the `tox.ini` config. Well, it's probably a matter of taste where do you want to have all your options. However, if you add it to `setup.cfg`, you can also add options for `flake8`. That way, you have everything in **one place**.
* I'm not sure if coverage is useful for such a small script. To have an oversight of which lines are not covered by tests yet *could* be useful. At the moment I get:
``` …
```

Create setup.cfg for pytest & tox config and coverage

---

CHANGELOG
semver.py
test_semver.py

Continuation of stale #104 with fix for Python2

Fix comparison

---

docs/conf.py
docs/requirements.txt
tox.ini

This PR contains the following change and fixes #126 :
* Add "docs" target to run sphinx and output HTML
* Provide `docs/requirements.txt` file
* Fix typo in `docs/conf.py`
----
Some comments:
* You could run the `docs` target through Travis, same as with the other targets. However, I wasn't sure if this would be useful for you, because you may create the doc with something else.
* I've provided a separate requirements.txt file only for documentation. That way you can add whatever is needed without changing the `tox.ini` file.
* The result of the build can be found at `dist/docs`.

Fix #126: Provide tox.ini for documentation

---

semver.py
test_semver.py

This PR implements #139 
* Add bump_major, bump_minor, bump_patch, bump_prerelease and bump_build as methods in class VersionInfo. With this methods, it is now possible to write something like this:
```python
ver = semver.parse_version_info("3.4.5")
new_ver = ver.bump_major().bump_minor()
```
* Add test cases
---
Some comments about this implementation:
* I (re)used the module functions `semver.bump_major()` etc. to avoid implementing the same code (double code is bad code).
* It may be not as efficient as it could be, because it converts the VersionInfo into a string, bumps it, and convert is back into VersionInfo. Not sure if there is a better way to do it.
* I've created a "Draft pull request" so we can discuss and improve the code. ;-)
@ppkt Karol, what do you think? :-)

Implement #139: Bump version inside VersionInfo

---

.travis.yml
tox.ini

This PR fixes #145 
Without the posargs argument tox has to run the *complete* test suite. With this patch, you can
pass a test file and a test function. That allows tox to only run this specific test function. For example:
```
$ tox -e py36 test_semver.py::test_should_bump_major
```
Keep in mind, it doesn't change the default behavior. It's just an additional feature if someone wants to run a single test function alone.
This may help to speed up the development a little bit. :wink:

Fix #145: add posargs in tox.ini (single test cases)

---

docs/development.rst

This PR fixes #148 and contains:
As tox discouraged using "python setup.py test", we shouldn't recommend that in our documentation. Replacing it with `tox`.

Fix #148: Remove & replace python setup.py test

---

MANIFEST.in

This PR fixes #136 and adds the `test_semver.py` file into the tarball when running `python setup.py sdist`.
---
Comments:
* I've added a glob pattern in the `MANIFEST.in` file (`test_*.py`) in case we add some more test files.

Fix #136: add testsuite to tar ball

---

.coveragerc
test_semver.py

This PR is not based on an issue, but it with this change, it raises the coverage level. Currently I get:
```
----------- coverage: platform linux, python 3.6.5-final-0 -----------
Name        Stmts   Miss Branch BrPart  Cover   Missing
-------------------------------------------------------
semver.py     198      0     50      2    99%   38->43, 513->517
```
Line 513-517 belongs to the `_increment_string()` function. I wasn't sure how to cover it as it is indirectly called by `bump_prerelease()` and `bump_build()`. Any idea is very appreciated. :+1:

Improve coverage

---

semver.py
test_semver.py

This PR fixes #135 
Creating `VersionInfo(3, 2, 1, 1)` succeeds, but fails later when comparing it with another `VersionInfo` instance (for example, v1 < v2):
```
def split_key(key):
>       return [convert(c) for c in key.split('.')]
E       AttributeError: 'int' object has no attribute 'split'
```

Fix #135, convert prerelease and build to string

---

README.rst
docs/conf.py
docs/index.rst
docs/readme.rst
docs/usage.rst
semver.py

* Improve README and describe a short session with parsing a version string and access the different parts of a version.
* Include README (=Quickstart) as part of the documentation.
* Add missing docstrings for properties

Fix #154: Improve Description on PyPI

---

setup.py

Small fix, but should solve problem from #119 - original clean command will be executed before our code so parsing arguments should work as intended.

Invoke clean from distutils before running our code

---

conftest.py
semver.py
setup.cfg

This PR is not based on a specific issue, but contains the following changes:
* Introduce `conftest.py` to add pytest fixture for `doctest_namespace`
See https://docs.pytest.org/en/latest/doctest.html#doctest-namespace-fixture
* Remove the "import semver" line in each doctest; this is covered in `conftest.py` now as a pytest fixture
* Extend `setup.cfg` with `--doctest-report ndiff`
Makes the output a bit nicer in case something goes wrong
* Make sure, the docstrings are consistent:
* First line is a summary
* Followed by a linebreak and the description of the parameters
* Optionally with a doctest

Improve doctests

---

CHANGELOG.rst
docs/changelog.rst
docs/conf.py
docs/index.rst

This PR fixes #159 and contains the following changes:
* Rename `CHANGELOG` -> `CHANGELOG.rst`
* Adapt the changelog:
* Group the issues into the sections "Bug Fixes", "Features", "Removals"
* Change wording of past tense into present tense
* Try to sort issue number from low to high to make it consistent
* Add missing 2.8.2 release
* Prepare version 2.9.0 as WIP
* Include `CHANGELOG.rst` into documentation (through the new file `docs/changelog.rst`)
* Introduce "extlinks" to `docs/conf.py` to allow linking to GitHub issues and pull requests.
When using :gh:\`123\` it is automatically converted into a link that points to the corresponding GitHub issue (same for pull requests with :pr:\`234\`).
---
Some comments:
* I've introduced a new role in Sphinx: `gh` and `pr`. This turns GitHub …

Fix #159: Improve Changelog

---

CHANGELOG.rst
docs/usage.rst
semver.py

This PR fixes #167 and implements the global SEMVER_SPEC_VERSION constant.

Fix #167: Introduce SEMVER_SPEC_VERSION

---

.coveragerc
CHANGELOG.rst
test_semver.py

This PR does not belong to an issue. It contains the following changes:
* Add test for (private) `_increment_string()` function
* Adapt `.coveragerc`:
* Introduce option precision; 
* Disable coverage for `cmp()` function
---
With the above modifications, coverage is raised to 100%. :wink:

Improve code coverage

---

CHANGELOG.rst
docs/cli.rst
docs/conf.py
docs/index.rst
docs/requirements.txt
semver.py
setup.py
test_semver.py

This PR fixes #59 and contains the following changes:
* Extend setup.py with entry_point key and point to `semver.main`. The script is named `semver`
* Introduce 3 new functions:
* `createparser`: creates and returns an `argparse.ArgumentParser` instance
* `process`: process the CLI arguments and call the requested actions
* `main`: entry point for the application script
* Add test cases:
* sort import lines of semver functions/class with isort tool
* sort list of SEMVERFUNCS variable
* Extend documentation:
* Add `sphinx-argparse` as a doc requirement to document `semver` script (subcommands and options)
* Include new `cli.rst` file which (self)documents the arguments of the semver script using the `sphinx-argparse` plugin
* Extend extensions variable in `conf.py` to be able to use the …

Fix #59: Implement command line interface

---

CHANGELOG.rst
docs/usage.rst
semver.py
test_semver.py

This PR fixes #144 and contains:
* `semver.replace(version: str, **parts: dict)`
* `semver.VersionInfo.replace(**parts: dict)`
* Extend the usage documentation
* ~~Adapt `format_version()` function. This function accepts strings in the major, minor, and patch parts now. It was necessary as it makes the implementation of `semver.replace()` a bit easier.~~
* Both `replace()` functions raises a `KeyError` exception if you pass invalid keys. This makes the API consistent. 
My original implementation just delegate it to the respective function; however, that leads to different exceptions raised (`TypeError` or `ValueError`).
Both do almost the same: it replaces parts of a version string or a `VersionInfo` object and creates a new object (with the changed parts).
**Update 2019-10-12:**
The …

Fix 144: Add replace function

---

CHANGELOG.rst
README.rst

This PR extends the README with a note about the move to a new GH organization.
Mentioned in #177 and #178

Add note for GH repo to new python-semver org

---

docs/_static/css/default.css
docs/conf.py

This PR contains a fix to correct the logo:
* Correct the size of the logo
* Add white background
I don't know if this is the preferred method. However, I haven't found a configuration option to modify the size of a logo.
Example screenshot
----

Correct logo width, add white background

---

CHANGELOG.rst
semver.py
test_semver.py

This PR fixes #192 and contains the following changes:
* Raise SystemExit when `pysemver` is called without arguments.
* When `pysemver bump` is called without arguments, print the help text for the bump subcommand and exit.
* Add test cases for both calls.
Without this patch, `pysemver bump` raises an AttributeError:
```
Traceback (most recent call last):
File ".tox/py36/bin/pysemver", line 8, in <module>
sys.exit(main())
File ".tox/py36/lib/python3.6/site-packages/semver.py", line 726, in main
result = process(args)
File ".tox/py36/lib/python3.6/site-packages/semver.py", line 693, in process
if args.which == "bump":
AttributeError: 'Namespace' object has no attribute 'which'
```
---
Funny sidenote: I discovered this bug when trying to document the manpage. :wink:  Documenting reveals …

Fix "pysemver" and "pysemver bump" when called without arguments

---

CHANGELOG.rst
docs/install.rst

This PR fixes #196 
* Improve the installation section and add installation instructions for Arch Linux, Debian, Fedora, FreeBSD, openSUSE, and Ubuntu.
* Adapt `CHANGELOG.rst`
----
I've mostly used the installation instructions from https://pkgs.org, but I'm not sure if this is all correct (I mainly use openSUSE). So please check, if this is ok.

Add distribution specific install hints

---

docs/install.rst

This PR is not based on a specific GH issue. Should be fairly easy to review. :wink: 
The pull request contains the following changes:
* Add missing install command for FreeBSD
* Introduce a "Pip" and "Linux Distributions" subsections
* Change header level of every distribution (to make it appear  under the "Linux Distributions" subsection)
* Move note into "Linux Distributions" subsection

Doc: Correct missing parts in installation section

---

.github/workflows/black-formatting.yml

This PR is a first start of GH Actions to call the `black` source code formatter and does basically this:
1. Triggered by a pull request event.
2. Setup Python 3.7.
3. Install black.
4. Run black and create a diff file.
5. Upload the diff as artifact; this can be downloaded and examined if needed. See my [action run in my fork](https://github.com/tomschr/python-semver/pull/2/checks?check_run_id=318204067).
For the time being, it's quite "simple". This was on purpose as I've played with other fancy stuff which didn't work as expected (probably it was my fault because this topic is quite new for me).
From a design point of view, it is built upon other actions, created by GitHub itself.
At the moment, black creates a >50KB diff of the source code of all `*.py` files. Maybe we should create …

Extend #186: Add GitHub Action for black formatter

---

semver.py
setup.py
test_semver.py

I took a regex from https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string , splitted it into multiple lines to match current format and renamed `buildmetadata` -> `build`. Also, I found and fix a problem with invalid Python 2.7 super call :)

Fix #194 and #114: Update semver regex to version from semver.org

---

CHANGELOG.rst
README.rst
docs/conf.py
pyproject.toml
semver.py
setup.cfg
setup.py
test_semver.py

* Add `pyproject.toml` containing black configuration
* Add batch image in `README.rst`
* Reformat source code with `black` (version 19.3b0)
Keep in mind, `black` reformats the code quite drastically. That means, all open pull requests will fail to merge. Maybe we should finish and merge pr #138?
---
You will notice, due to #200, the "Check" tab contains now two checks: one for Travis and another one with the GitHub Action for Black. Currently, the black formatting has zero diffs. :+1:

Fix #201: Reformat source code with black

---

.github/workflows/black-formatting.yml

* Remove uploading the diff file as artifact
* Use `--check` to test our source code
---
I haven't provided an entry in the CHANGELOG. It doesn't affect the source code and it's not bound to a specific release, so I thought I skip this. Hope this is ok. :wink:

Fix #203: Use --check option for black (infra)

---

tox.ini

This PR contains (not related to any issue):
* Describe each target with `description` keyword; useful when running `tox` as `tox -a -v`
* Move `whitelist_externals` to `textenv` section
* Use `make` in `docs` target instead of running `sphinx-build` directly
* Introduce `black` target to check for changes in formatting
* Use `posargs` for flake
---
I didn't update the CHANGELOG as it is not related to the source code, more about the infrastructure. For end-users, I think, it is not of much interest *how* we create this project (as long as we describe changes in the source code). Nevertheless, if this is still of interest, I could introduce a separate section ("Infrastructure").

Improve consistency in tox.ini

---

setup.py

This PR contains a one-liner:
* Add `python_requires` in `setup.py`
It can be useful as it fails fast when the developer uses an incompatible Python version.

Add python_requires keyword in setup.py

---

CHANGELOG.rst
docs/pysemver.rst
docs/usage.rst
semver.py
test_semver.py

This PR fixes #208 and contains:
* `VersionInfo.isvalid(cls, version:str) -> bool`
* Add test case
* Describe function in documentation; also clarified in the "Creating a Version" what happens when the user pass an invalid version string.
As I expect some discussions and as this is still WIP, I haven't completed the CHANGELOG entry yet. :wink: 
---
Update 2019-12-08: Add entry in `CHANGELOG.rst`.
---
Update 2019-12-09: Insert `check` subcommand into `pysemver` command.

Fix #208: Introduce VersionInfo.isvalid() function

---

.travis.yml
CHANGELOG.rst
semver.py
tox.ini

This PR contains the following changes (not related to an issue).
* Use `docformatter` from https://github.com/myint/docformatter/
* Reformat `semver.py` to be compatible with PEP257 docstrings
with `docformatter -i --pre-summary-newline semver.py`
* `tox.ini`
- Introduce `docstrings` target which calls `docformatter`
to check for PEP257 compatible docstrings
- Introduce a new `check` target which calls `black`, `flake8`, and
`docstrings`
* `.travis.yml`
Run `check` target instead of `flake8`
@bittner: Would you like to have a look? :wink: 
---
I realized, that the Black GitHub Action is maybe a bit one dimensional. It could contain the other checks that I've introduced in this PR (black/flake8 for source codes, docformatter for docstrings).
Should I extend the GH Action and add the other …

Improve docstrings according to PEP257

---

docs/pysemver.rst
semver.py
test_semver.py

This PR is not based on a specific issue, but is a refactoring effort to improve maintenance of the `pysemver` subcommands:
* Use separate `cmd_*` functions for each subcommand (basically, I've moved the if...elif clauses from `process` into separate functions).
* Replace `which` with `func` keyword.
* Use `func` keyword to store the specific `cmd_*` function.
* Adapt tests.
* (Re)format with `black`.
* Clarify how to interpret return code in manpage (add new section "Return Code").
=> Easier to extend subcommands

Improve pysemver subcommands

---

CHANGELOG.rst
docs/usage.rst

* Document how to deal with invalid versions
* Use `coerce(version)` as an example

Fix #210: how to deal with invalid versions

---

CHANGELOG.rst
MANIFEST.in
release-procedure.md
semver.py
setup.py

This PR fixes #219:
* Raise version number in `__version__`
* Update CHANGELOG
* Mention TestPyPI in `release-procedure.md`
* MANIFEST.in:
* Exclude `.travis.yml`
* Exclude `.github` directory (pretty useless in an archive/wheel)
* Exclude `docs/_build` directory
* Exclude temporary Python files like `__pycache__`, `*.py[cod]`
* Include all `*.txt` and `*.rst` files
---
Update 2020-02-16: Add missing issue number

WIP: Create semver version 2.9.1-rc2

---

CHANGELOG.rst
setup.py

This PR is a first attempt to fix #224 and contains:
* In class clean, replace super(CleanCommand, self).run() with CleanCommand.run(self)
Co-authored-by: Dennis Menschel <menschel-d>
@menschel-d could you try this branch and test it?

Fix #224: Replace super() call

---

CHANGELOG.rst
README.rst
conftest.py
docs/coerce.py
docs/development.rst
docs/usage.rst
setup.cfg

This PR is not based on a specific issue; it just evolved after having the idea of better integrate doctests in our documentation with pytest. :wink: 
Our documentation contains some examples which can be considered as doctests. As pytest supports doctests, we could use this features to check if the examples in our documentation are still correct.
* Fix typos in `README.rst`.
* Move `coerce()` function into separate file; this was needed so it can be both included into the documentation and inside `conftest.py`.
* In `docs/usage.rst`:
- Fix typos
- Add missing semver module name as prefix
- Slightly rewrite some doctests which involves dicts (unfortunately, order matters still in Python2).
* In `setup.cfg`:
- Add `--doctest-glob` option to look for …

Add better doctest integration into pytest

---

semver.py

This PR contains some minor fixes in docstrings only:
* Use `.. versionadded::` RST directive in docstrings to make it more visible when something was added
* Minor wording fix in docstrings (versions -> version strings)

Add version information in some functions

---

.gitignore
CHANGELOG.rst
docs/usage.rst
semver.py
setup.cfg
test_semver.py

This PR fixes #225. 
For example, the `VersionInfo.bump_major()` method calls `semver.parse_version_info` and `semver.bump_major` instead of having its own implementation. This has several drawbacks:
* the VersionInfo class depends on other, "remote" function outside the class.
* the class is not "self-contained".
* it makes deprecating module level functions (and removing them) harder because of these dependencies.
As such, I had to move some implementation into the `VersionInfo` class. With this approach, we can deprecate the module level function without triggering a false positive when calling a method in `VersionInfo`.
* Add test cases
- Test also missing `finalize_version`
- Test the warning more thouroughly with `pytest.warns` instead of just …

Deprecate module level functions

---

CHANGELOG.rst
README.rst
docs/pysemver.rst
docs/usage.rst
semver.py

This PR is not based on a specific issue.
As we had deprecated module-level functions now, we shouldn't advertise it in our documentation too much.
Module level functions like `semver.bump_version` are still available in the documentation, but they play a much less important role now. The preferred way is to use `semver.Versioninfo` instances to use.
@python-semver/reviewers I guess it's easy to review and contains only doc changes. :wink: If noone objects, I will merge it on Monday.

Shift focus on semver.VersionInfo.* functions

---

docs/usage.rst
semver.py
test_semver.py

This PR contains (based on #221):
* Implement semver.next_version(version, part, *, prerelease_token="rc")
* Add test cases
TODOs:
----
@gsakkis This is a first draft, feel free to comment. :wink:

First implementation of next_version

---

CHANGELOG.rst
docs/usage.rst
semver.py
test_semver.py

This PR is a fresh implementation of #138 and contains:
* Add `__getitem__` to `VersionInfo` class
* Add test cases
* Add user documentation
* Extend CHANGELOG
----
@tlaferriere, @bittner: As pr #138 was a bit older and a lot of things have changed now, I've created a fresh new branch so we won't get any conflicts. On top of that, I've added the implementation. If you would like to have a look, that would be great. :+1:

Implement __getitem__ for #138

---

CHANGELOG.rst
docs/usage.rst
semver.py
test_semver.py

This PR fixes #244 and contains the following changes:
The `VersionInfo.compare` method allows already `VersionInfo`, dict, tuple/list and str.
* Extend list of allowed types in `comparator` with list and str.
* Rewrite case `test_should_not_allow_to_compare_version_with_string` ->
`test_should_compare_version_string`
* Add new test cases:
- `test_should_compare_version_list`
- `test_should_not_allow_to_compare_invalid_versionstring`
* Use `pytest.mark.parametrize` for `test_should_compare_version_tuples`
* Update `usage.rst` to document all possibilities
* Update `CHANGELOG`

Fix #244: Allow list & str for comparison

---

semver.py

This PR is not based on a specific issue.
This PR just defines default behavior when executing `from semver import *` (although it's considered bad coding practice).
See also:
https://docs.python.org/3/tutorial/modules.html#importing-from-a-package
---
As this is kind of minor change, I would merge it on Monday if nobody objects.

Add __all__ to provide explict index of semver

---

docs/install.rst

Use `obs://` scheme instead of the longer `http://`. The former has the additional advantage, that the current release is automatically detected.
@m-rey: Would that be ok?

Simplify openSUSE installation with obs://

---

docs/install.rst

This PR is not based on any specific issue. It's a doc-only addition.
---
Add a new section "Release Policy" to give a recommendation for users who wants to stay for major release 2.
As with the upcoming major 3 release of semver, a lot of things have been changed. To avoid any surprises for our users or even break their code base, a short version restriction can solve that.
Basically, it boils down to a line like `semver>=2,<3`. This can be added in any file which lists dependencies.

Doc: Add version rule to avoid surpises

---

semver.py

This PR is not based on a specific issue. It contains the following changes:
* Use `VersionInfo` instead of `semver.VersionInfo`
* Change order. Deprecation notice should come first in docstring

Make docstrings consistent

---

docs/install.rst

This PR contains: The `install` command for `zypper` was missing.

Doc: Add missing "install" for openSUSE

---

CHANGELOG.rst
docs/usage.rst
semver.py
test_semver.py

This could close #160 .
As I said in this [comment](https://github.com/python-semver/python-semver/issues/160#issuecomment-642328641), this PR will deprecate functions that could be useful as a shortcut.
As you can see in the new examples in the documentation, it is quite a mouthful to find the maximum of two version strings.
As an alternative to this we could keep `max_ver` and `min_ver` as utility functions that automatically convert from whatever supported types we have, passes them to `max` or `min` then converts back into the input types to return them.

Deprecate `max_ver` and `min_ver`

---

docs/development.rst

No related issue.
This PR contains:
For contributing to semver, every substantial change should also introduce a Sphinx directive (`versionadded`,
`versionchanged`, or `deprecated`) to help our readers.

Doc: Mention Sphinx directive for docstrings

---

CHANGELOG.rst
CONTRIBUTORS
docs/usage.rst
semver.py
setup.cfg
test_typeerror-274.py

This fixes #274 and contains:
fixes problems between different string types. In Python2 `str` vs. `unicode` and in Python3 `str` vs. `bytes`.
---
@eli-darkly I've tried to recycle some code from the six project. Maybe there is an easier way, maybe we can improve some ugly code. Would you like to have a look at? Thank you! :heart:

Fix #274:  String Types Py2 vs. Py3 compatibility

---

CHANGELOG.rst
semver.py

This fixes #288 and contains:
* #274 / #275 String Types Py2 vs. Py3 compatibility
* #277 Turn VersionInfo.parse into classmethod to allow subclasses
* #286 Add author and update changelog for #276/#277

Prepare 2.11.0 release

---

CHANGELOG.rst
docs/usage.rst
semver.py
test_semver.py

This PR fixes #291 and contains the following change:
Disallow negative numbers of `major`, `minor`, and `patch` in `semver.VersionInfo.`
Reason: a version can only contain positive numbers
@tlaferriere This is the corresponding pull request. Maybe there are better ways to do it. :wink: 
I would release 2.12.0 if you think this is useful.

Fix #291: Disallow negative numbers in VersionInfo

---

docs/usage.rst
semver.py
test_semver.py

Per [the python datamodel](https://docs.python.org/3/reference/datamodel.html#object.__hash__), `a == b` implies `hash(a) == hash(b)`. The current implementation of `VersionInfo.__hash__` includes the build, which isn't used for equality.

Ensure equal versions have equal hashes

---

.travis.yml
README.rst
setup.py
tox.ini

This PR contains:
* Update README.rst and NOT mention specific versions. Use "2.x.y" as versions can change.
* Support Python 3.8/3.9 for semver2

Support latest Python version for semver2

---

docs/requirements.txt

This should (hopefully) fix #297 as it disables `sphinx-argparse`. It's not needed anymore.

Doc: Disable sphinx-argparse

---

changelog.d/313.trivial.rst
tox.ini

This PR contains only a single change: add `skip_install = true`. This speeds up the execution of towncrier.
As we only need to install towncrier, it is not necessary to install semver too. Therefor, we skip the installation of semver.

Tox: skip installation for changelog target

---

changelog.d/310.bugfix.rst
docs/_api/semver.__about__.rst
docs/_static/css/custom.css
docs/api.rst
docs/conf.py
src/semver/__about__.py
src/semver/_types.py
src/semver/cli.py
src/semver/version.py
tests/conftest.py
tox.ini

This PR fixes #310 and contains:
* Remove all automatic generation and use a more "semi-manual" approach (gives more control)
* Improve docstrings in semver module
* Remove docstrings in some dunder methods; Sphinx and autodoc uses the docstring from the parent class
* Remove sphinx-apidoc command from `tox.ini`

Fix #310: Correct API documentation

---

CHANGELOG.rst
changelog.d/213.improvement.rst
changelog.d/312.doc.rst
docs/semverwithvprefix.py
docs/usage.rst

This PR fixes #312 and contains the following changes:
* Correct `:class:` directive and use `:class:~semver.version.Version`
* Mention the rename of VersionInfo -> Version class
* Remove semver. prefix in doctests to make examples shorter
* Correct some references to dunder methods like `__getitem__`, `__gt__` etc.
* Use `:py:exec:` reference to Python exceptions.
* Remove inconsistencies and mention module level function as deprecated and discouraged from using
* Use empty `super()` call in `semverwithvprefix.py` example instead of the more verbose `super(SemVerWithVPrefix, self)`

Improve usage section

---

changelog.d/316.trivial.rst
src/semver/version.py

The former code raised a `TypeError` exception for comparisons like `__gt__`, `__lt__` etc. to indicate a wrong type.
However, according to [NotImplemented](https://docs.python.org/3/library/constants.html#NotImplemented) documentation, we should return(!) NotImplemented (not raise) when a comparison with an invalid type is not implemented.

Fix #316: Return NotImplemented for comparisons

---

.travis.yml
changelog.d/319.trivial.rst

The config file contains now two stages: check and test. If check fails, the test stage won't be executed. This could speed up things.
Additionally, the config file was cleaned up to remove entries of `mypy` as this is already included in the `check` target.

Introduce stages in .travis.yml

---

changelog.d/309.trivial.rst
docs/api.rst
src/semver/version.py
tests/test_typeerror-274.py

This PR fixes #309 and contains:
* Rename `comparator` -> `_comparator`, `cmp` -> `_cmp`
* Remove `ensure_str` and integrate it into `Version.parse`
* Rework tests in `test_typeerror-274.py`
* Move `_nat_cmp` to `Version` and make it a class method
* Remove private functions from API documentation

Fix #309: Make some functions private

---

CONTRIBUTING.rst
README.rst

* Remove Gitter badge
* Add GitHub Discussions badge
* Amend Contributing with link to GH Discussion page

Add badge to GitHub Discussion

---

docs/usage.rst

This simple fix makes tests pass with Python 3.10. Without it, the error is:
```
453   If the dictionary contains unknown keys, you get a :class:`TypeError` exception::
454 
455     >>> v > dict(major=1, unknown=42)
Differences (ndiff with -expected +actual):
Traceback (most recent call last):
- ...
+   File "/usr/lib64/python3.10/doctest.py", line 1340, in __run
+     exec(compile(example.source, filename, "single",
+   File "<doctest usage.rst[75]>", line 1, in <module>
+     v > dict(major=1, unknown=42)
+   File "/builddir/build/BUILD/python-semver-2.13.0/semver.py", line 203, in wrapper
+     return operator(self, other)
+   File "/builddir/build/BUILD/python-semver-2.13.0/semver.py", line 589, in __gt__
+     return self.compare(other) > 0
+   File …
```

Fix tests for Python 3.10

---

docs/migratetosemver3.rst
docs/usage.rst
src/semver/_deprecated.py
src/semver/_types.py

I was reading through the documentation and thought that the suggestion for finding max/min of a list/iterable of strings using `semver` unecessarily complicated, with a `map`, and multiple typecasts. I think using just `max` with `key` as done in this PR is much cleaner and should be the de-facto suggestion.
This is my first contribution to this repository, I hope it's welcome and I've followed the contribution guide well - but feel free to let me know if I can improve anything or close this PR if it's unwanted :)

Improve suggestion for finding max and min using semver

---

changelog.d/335.doc.rst
docs/advanced/convert-pypi-to-semver.rst
docs/advanced/index.rst
docs/conf.py
docs/install.rst
docs/migration/replace-deprecated-functions.rst
tests/conftest.py

This PR contains:
A new section "Converting versions between PyPI and semver". Add limitations and possible use cases to convert from one into the other versioning scheme.
<details>
<summary>Screenshot of the new topic (click me)</summary>
</details>
Related issue: #335

Describe conversion between PyPI and semver

---

changelog.d/pr359.feature.rst
docs/usage/parse-version-string.rst
src/semver/version.py
tests/test_parsing.py

For my personal use I added the possibility to parse a version string that is shorter than `major.minor.patch`, for example `13.5`.
When creating a semver version object using the constructor it is possible to only pass a major version and the other parameters are filled with a default value. So why not give this possibility to the parsing function.
To keep backwards compatibility and the requirement from semver that normal version strings need at least three version numbers, the parsing of shorter version strings must be enabled with a parameter. Without that parameter the old functionality will be executed.
I do not know if this is something you would like to integrate, if not simply close this pull request. Otherwise give me a short feedback, then I will update the documentation and …

Allow shorter version for parsing

---

changelog.d/pr362.feature.rst
docs/usage/compare-versions-through-expression.rst
src/semver/version.py
tests/test_match.py

This makes it easier to work with user-supplied versions, as they may omit the comparison operator and just specify which version they want to select. Equality comparison is a sane default behavior.

Support matching 'equal' when no operator is provided

---

changelog.d/374.bugfix.rst
pyproject.toml

* Replace the old, deprecated ``[[tool.towncrier.type]]`` entries with ``[tool.towncrier.fragment.<TYPE>]``. Described in https://towncrier.readthedocs.io/en/stable/configuration.html#deprecated-defining-custom-fragment-types-with-an-array-of-toml-tables
* Add a changelog news file
@Nagidal: would you like to review it, please? :pleading_face:

Fix #374: Adapt pyproject.tom for Towncrier

---

.github/workflows/python-testing.yml
BUILDING.rst
CONTRIBUTING.rst
README.rst
pyproject.toml
setup.cfg
setup.py
tox.ini

Python 3.6 reached its end of life and isn't supported anymore. At the time of writing (Dec 2022), the lowest version is 3.7.

Fix #372:  Remove support for Python 3.6

---

.github/workflows/python-testing.yml
.gitignore
MANIFEST.in
changelog.d/pr384.bugfix.rst
docs/advanced/semverwithvprefix.py
pyproject.toml
setup.cfg
src/semver/version.py
tests/test_match.py
tox.ini

* Reformat source code with black again as some config options did accidentely exclude the semver source code. Mostly remove some includes/excludes in the black config.
* Integrate concurrency in GH Action
* Ignore Python files on project dirs in `.gitignore`
* Remove unused patterns in MANIFEST.in
* Use extend-exclude for flake in setup.cfg and adapt list.
* Use `skip_install=True` in `tox.ini` for black

General cleanup, reformat files

---

changelog.d/388.trivial.rst
setup.cfg
tests/conftest.py
tox.ini

Switch to the more modern importlib approach as it doesn't require to modify `sys.path`:
https://docs.pytest.org/en/7.2.x/explanation/pythonpath.html

tox/pytest: Add testpaths and use importlib

---

changelog.d/pr392.doc.rst
docs/advanced/combine-pydantic-and-semver.rst

The current example, when used with semver 3.0.0.dev4 and pydantic 1.10.4, produces the following error:
```
Traceback (most recent call last):
File "/home/msalvatore/compost/semver_test/test.py", line 19, in <module>
class MyModel(pydantic.BaseModel):
File "pydantic/main.py", line 198, in pydantic.main.ModelMetaclass.__new__
File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
File "pydantic/fields.py", line 557, in pydantic.fields.ModelField.prepare
File "pydantic/fields.py", line 834, in pydantic.fields.ModelField.populate_validators
File "pydantic/class_validators.py", line 263, in pydantic.class_validators.prep_validators
File "pydantic/class_validators.py", line 259, in …
```

Fix pydantic/semver example

---

src/semver/__main__.py

This was caused by \_\_main\_\_.py passing `sys.argv` to `cli.main()`, which includes the path of the script in `sys.argv[0]`. `argparse.ArgumentParser.parse_args()` parses this as the subcommand name, causing it to throw an error.
This could also be fixed by removing `sys.argv` entirely from [the arguments passed to `cli.main()`](https://github.com/python-semver/python-semver/blob/master/src/semver/__main__.py#L28), as [`argparse.ArgumentParser.parse_args()` will use `sys.argv[1:]` by default](https://github.com/python/cpython/blob/3.11/Lib/argparse.py#L1871).
I'm not sure if this change warrants an added test, as the existing tests cover `cli.main()` directly, but such a test would be reasonably straightforward to create and I can do so if you like.

Fix: All `python -m semver` commands fail with 'error: invalid choice:'

---

src/semver/version.py

So that calling parse on a derived class will show correct type of derived class

Fix return type of classmethod parse

---

changelog.d/344.bugfix.rst
docs/usage/increase-parts-of-a-version_prereleases.rst
docs/usage/raise-parts-of-a-version.rst
src/semver/version.py
tests/test_bump.py

The methods `.bump_prerelease('')` and `.bump_build('')` generates a prerelease and build part without the token.

Fix #344 Allow empty string for bump method

---

setup.cfg

The asterisk in `python_requires = >= 3.7.*` of `setup.cfg` make the `pyproject-build` command fail with this exception:
setuptools.extern.packaging.specifiers.InvalidSpecifier: Invalid specifier: '>=3.7.*'
This fix removes the asterisk which leads to a successful build.

Fix #397: Remove asterisk in python_requires

---

.gitignore
changelog.d/284.deprecation.rst
changelog.d/284.doc.rst
changelog.d/284.feature.rst
docs/conf.py
docs/migration/migratetosemver3.rst
docs/migration/replace-deprecated-functions.rst
docs/usage/check-compatible-semver-version.rst
docs/usage/check-valid-semver-version.rst
docs/usage/index.rst
src/semver/cli.py
src/semver/version.py
tests/test_semver.py
tox.ini

This is a first implementation of `Version.is_compatible`.
The algorithm checks:
* if the two majors are different, it's incompatible
* if the two majors are equal, but the minor of the callee is lower than the caller, it's incompatible
* if both prereleases are present and different, it's incompatible
* otherwise it's compatible
@rafalkrupinski /@sbrudenell / @Lexicality maybe you want to try/review it? :slightly_smiling_face:

Fix #284: implement "is compatible with" method

---

src/semver/_deprecated.py

Use `max()` and `min()` with argument `key=Version.parse`. This makes the two functions consistent.

Simplify max_ver and min_ver

---

pyproject.toml
tox.ini

Remove `wheel` and `build` dependencies from `pyproject.toml`. The former is added automatically by setuptools and is incorrect for sdist, the latter is frontend rather than backend.
(described in detail in commit messages)

Remove incorrect dependencies from build-system section of pyproject.toml

---

src/semver/version.py

Hi! Thanks for creating the python package. I am actually using it and stumbled across this typo.

correct typo in function description of `next_version`

---

.github/workflows/python-testing.yml

* Set timeout-minutes time to 15min
* Add on.push.path on.pull_request.path
* Raise Python 3.7 -> 3.8
* Use cache for actions/setup-python@v3
Ideas taken from https://ashishb.net/tech/common-pitfalls-of-github-actions/

Improve GitHub Action

---

CITATION.cff
release-procedure.md

Benefits:
* Users of our software can easily cite it using the metadata from `CITATION.cff`
* GitHub shows the citation information in the sidebar
* Browser plugins can import the correct reference
Sources:
* https://citation-file-format.github.io/
* https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

Add CITATION.cff for citation

---

changelog.d/pr418.bugfix.rst
docs/usage/convert-version-into-different-types.rst
docs/usage/create-a-version.rst
src/semver/version.py

dict is guaranteed to preserver order in all supported versions
Replaces #418

Return dict instead of OrderedDict

---

.github/workflows/python-testing.yml
changelog.d/426.bugfix.rst
src/semver/version.py
tests/test_subclass.py

This fixes PR #426 
When using the replace method, an instance of the Version class is created and not the subclass. This commit fixes this behavior.
@dannystaple: Could you have a look, please? :slightly_smiling_face: 
(The CI has currently problems. I'm currently investigating this.)

Fix #426: call subclass when deriving from Version

---

.github/workflows/python-testing.yml

The GHA seems to be "blocked" when no files under `on.push.paths` are triggered, for example, doc files.
This is an attempt to fix this issue. It can go nowhere as it's just a test.

GH Action: Don't block when only doc files are modified

---

changelog.d/460.bugfix.rst
docs/usage/raise-parts-of-a-version.rst
src/semver/version.py
tests/test_bump.py
tests/test_pysemver-cli.py
tox.ini

This PR fixes #460 and contains the following changes:
* Bumping an existing prerelease always results in a newer prerelease
* Bumping an empty prerelease can optionally bump the patch version to ensure a newer version
I ran the test suites successfully, except for 'checks', which also failed before I made any change. I ensured I did not introduce any new errors in this suite. I also added quite a bunch of tests to validate the new functionality, and adjusted a few that changed due to changing existing functionality.
Open to any suggestions for improvement, as my Python experience is a bit limited :-)

Fix #460 Improve bump_prerelease to alway get a newer version
