README.rst

Noticed this while debugging the use of the lib. Double checked it by running the tests: they are all OK.

Updated the README.rst to show the actual output

---

semver.py
tests/semver_test.py

- allow bumping major, minor, and patch parts
- ignore prerelease and build extensions if present
- added format_version function

Allow bumping of major, minor, and patch version parts.

---

README.md

I forgot to update the `README`. Thanks for accepting my contributions. Next time I'll batch them better. :)

Updated README with new usage examples

---

README.md
semver.py
setup.py
tests/semver_test.py

Added max_ver and min_ver APIs that work like the max() and min() of the
standard library when comparing ints. Includes tests and example in
README

Adds max_ver and min_ver APIs. Fixes #15

---

semver.py
tests/semver_test.py

Fix prerelease ordering

---

.travis.yml

This makes the build look nicer on Travis CI.

Make separate builds for tests on Travis CI

---

semver.py
setup.py
tests.py

I think, it is really important to have docstrings as a kind of good practice and for introspection when working in the interactive Python shell.
Find the pull request with docstrings and a small test case. ;-)
Hope you find it useful.

Improve Usability with Docstrings

---

semver.py
tests.py

This PR adds a `finalize_version` function, as described in #65.

Add finalize_version function

---

.travis.yml
setup.py
tox.ini

Remove Python 2.6 support

---

semver.py
tests.py

Closes #72, #73
Should help #74

Implements __str__ and __hash__

---

CHANGELOG
CONTRIBUTORS
release-procedure.md
semver.py

Release 2.8.0

---

README.rst
semver.py
test_semver.py

Static method parse for VersionInfo

---

CHANGELOG
semver.py
test_semver.py

prerelease and build set to None by default

---

semver.py

Update doc for format_version to match expected param types

---

CONTRIBUTORS
docs/conf.py
docs/development.rst

This PR fixes #85 and closes #115 and contains the following changes:
This is a mostly a complete rewrite, sometimes drastically, with the following ideas and changes in mind:
* Add a brief workflow, starting from forking, cloning, creating a branch, and opening a pull request.
* Use "procedure style" and use active voice to make reader aware of an action
* Remove intersphinx section of matplotlib (not used) in `docs/conf.py` (it seems just a leftover). Makes build faster.
---
I'm sure, I haven't addressed all ideas, so I see it as a first draft. We can always improve. So here are some of my questions and comments:
* Not sure if this chapter is a bit "overwhelming". Maybe we don't need to explain how to fork? To clone? To create pull request? Are these a given? Or should we address also …

Fix #85: Improve contribution section

---

README.rst

This PR is part of #161 and implements the items:
* Add the current document state/idea into the README
* Mention the plan for the 2.9.x "maintenance" branch

Add support state for Python 2.7/3.4 for #161

---

.gitignore
CHANGELOG.rst

This PR does not belong to a specific issue.
Taken most entries from https://github.com/github/gitignore/blob/master/Python.gitignore but adapt it this project.
----
I guess, this should be quite easy to review and merge. :wink:

Rework .gitignore

---

README.rst
release-procedure.md

Closes #171 
Remove Sphinx directives

Fix long description

---

CHANGELOG.rst
docs/conf.py
docs/logo.svg

Supersede PR #188 
Contains the following changes:
* Mentioned in issue #177
* Add logo to documentation
* Update CHANGELOG
Co-Authored-By: scls19fr

Fix #187: Create a squared logo

---

CHANGELOG.rst
semver.py
test_semver.py

@tomschr if you could take a look that would be appreciated.

Fix #251: Correct return type for next_version()

---

semver.py

Type should be VersionInfo instead of str in ``VersionInfo.bump_build`` and `VersionInfo.bump_prerelease`
@tlaferriere: could you have a look please?

Fix #252: Correct wrong str type in docstring

---

CHANGELOG.rst
release-procedure.md

* Update CHANGELOG
* Improve release-procedure.md
* Fix #251

Release 2.10.1

---

test_semver.py

Tried to cover everything but max_ver and min_ver since they might be deprecated.
I thought it could be nice to start off version 3 with 100% coverage

Increase coverage

---

CHANGELOG.rst
semver.py

* Update `CHANGELOG.rst`
* Raise version number

Prepare 2.10.2 release (#271)

---

semver.py
test_semver.py

Turn VersionInfo.parse into classmethod to allow subclasses

---

CHANGELOG.rst
CONTRIBUTORS

Just an omission for issue #276 and pr #277

Add author and update changelog for #276/#277

---

semver.py

* #291/#292 Disallow negative numbers in VersionInfo

Prepare 2.12.0 release (#293)

---

conftest.py
docs/semverwithvprefix.py
docs/usage.rst
setup.cfg
test_semver.py

This PR documents the subclass feature of issue #276.
@Anvil Damien, I forgot to add the documentation, so here it is! :wink: Would you be so kind and could have a quick look? It shouldn't be much.
Many thanks!

Document how to create subclass from VersionInfo

---

CHANGELOG.rst
CONTRIBUTORS
semver.py

This PR contains the following change:
* #283: Ensure equal versions have equal hashes

Prepare 2.13.0 release

---

docs/requirements.txt

Remove sphinx from requirements.txt

---

README.rst

This PR contains an update for the `README.rst` file:
* Add batch for isitmaintained.com
* Add batch for GitHub Action

Improve batches in README

---

CHANGELOG.rst

This PR just remove double entries in the changelog.

Clean changelog

---

.github/ISSUE_TEMPLATE/config.yml

This PR contains the following addition:
* Add file `config.yml`.
Configure the template chooser and provide some additional information.

Add config.yml for GitHub issues

---

.github/workflows/python-testing.yml
changelog.d/347.trivial.rst
pyproject.toml
setup.cfg
tox.ini

Inside GitHub Actions, config files etc.

Start supporting Python 3.10

---

changelog.d/343.doc.rst
docs/advanced/combine-pydantic-and-semver.rst
docs/advanced/index.rst

This PR adds a new section into "Advanced topic". Fixing #343.
@calebstewart would you mind having a look? Anything that is missing, wrong, or could be done better? Would be really helpful. Thank you very much! :heart:

Describe Pydantic and semver in "Advanced topics"

---

README.rst
docs/install.rst
setup.cfg
src/semver/__about__.py

Hello,
I noticed that all the URLs to be website were using HTTP instead of HTTPS. So I opened this PR to fix that since we are redirected to the HTTPS URL anyway.
If that was intended to use HTTP, please ignore this PR.

Use HTTPS instead of HTTP for the website URL

---

changelog.d/340.doc.rst
docs/advanced/index.rst
docs/advanced/version-from-file.rst

This PR fixes #340 and contains a new section about read a version from a file.

Add topic to read version from file

---

.github/workflows/python-testing.yml
BUILDING.rst
MANIFEST.in
changelog.d/364.feature.rst
docs/build.rst
docs/index.rst
pyproject.toml
setup.cfg
tox.ini

* Use setuptools
* Add metadata
* ~Use dynamic version from `semver.__about__.__version__`~ (set already in `setup.cfg`)
* ~Add build.sh script to call build module~ (not needed anymore)

Fix #365: Improve pyproject.toml

---

.github/workflows/python-testing.yml
src/semver/__main__.py
src/semver/_deprecated.py
src/semver/cli.py
src/semver/version.py

* Use v3 for some Actions
* Move to 3.11 instead of RC

CI: Update GH Actions

---

changelog.d/378.trivial.rst
pyproject.toml

Co-authored-by: Nagidal <nagidal@users.noreply.github.com>

Fix #378: Typos in Towncrier config

---

CHANGELOG.rst
CONTRIBUTORS
changelog.d/335.doc.rst
changelog.d/340.doc.rst
changelog.d/343.doc.rst
changelog.d/350.doc.rst
changelog.d/351.doc.rst
changelog.d/364.feature.rst
changelog.d/372.deprecation.rst
changelog.d/374.bugfix.rst
changelog.d/378.trivial.rst
changelog.d/pr359.feature.rst
changelog.d/pr362.feature.rst
docs/usage/semver-version.rst
src/semver/__about__.py

* Update CHANGELOG
* Adapt CONTRIBUTORS
* Fix small typos inside changelog.d/
* Raise version number

Create 3.0.0-dev.4 Release

---

changelog.d/pr389.trivial.rst
src/semver/version.py

This class variable contains a tuple of strings that contains the names of all attributes of a Version (like "major", "minor" etc).
In cases we need to have dynamical values, this makes it easier to iterate.

Trivial: Introduce public Version.NAMES class variable

---

CHANGELOG.rst
changelog.d/410.bugfix.rst
docs/usage/semver-version.rst
release-procedure.md
src/semver/__about__.py
tox.ini

* Raise version
* Ignore exit code from docformatter in checks `tox.ini`
* Correct typo in `release-procedure.md`
* Update `CHANGELOG.rst`

Prepare version 3.0.1

---

.github/workflows/python-testing.yml
changelog.d/pr417.feature.rst

GHA: Use matrix to test MacOS too

---

changelog.d/pr420.trivial.rst
pyproject.toml
src/semver/version.py

Use it for class variables `NAMES`, `_LAST_NUMBER`, `_REGEX_TEMPLATE`, `_REGEX`, and `_REGEX_OPTIONAL_MINOR_AND_PATCH`.

Introduce ClassVar type

---

changelog.d/pr421.trivial.rst
pyproject.toml
tox.ini

Add mypy config to pyproject.toml

---

docs/advanced/combine-pydantic-and-semver.rst

This PR contains the doc changes for #422.
@RobinGroundfog: could you have a look? If you want to build it, use `tox -e docs`.
<details>
<summary>Screenshot</summary>
</details>

Fix #422: Update advanced topic about Pydantic v2

---

changelog.d/pr436.doc.rst
docs/_static/css/custom.css
docs/_templates/layout.html
docs/conf.py

This makes it easier for users as if the TOC is long, the search box isn't visible anymore.

Move search box more at the top

---

src/semver/version.py

Pass black/flake8/mypy in both Python3.7 and Python3.12

Improve type hints to fix TODOs

---

.github/workflows/python-testing.yml

Gha add python313

---

src/semver/version.py

* Remove obsolete else
* Find a better way to identify digits without the re module
* Fix docstring in compare

Improve private _nat_cmp() method
